name: CI_PULL

on:
  pull_request:
    branches: [ dev , tommy-2, brian, franklee, frankli, Iain, how-to-page, set-up-page, try-cypress]
    # TO BE CHANGED since it should include the branch you're working on


defaults:
  run:
    working-directory: source
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run test
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx http-server -a localhost -p 5500 . &
      - run: npx cypress run
  HTMLHint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx htmlhint ./HTML/*.html
  Stylelint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx stylelint ./*.css
  ESlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npx eslint ./JS/*.js
  CommentsCoverage:
    runs-on: ubuntu-latest
    uses: romeovs/lcov-reporter-action@v0.2.16
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}